[[redirects]]
  from = "/api/*"
  to = "https://kenkoooo.com/atcoder/resources/problems.json"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://kenkoooo.com/atcoder/resources/problem-models.json"
  status = 200
  force = true
